index_path = "test_standard.bleve"
pbf_path = "liechtenstein-latest.osm.pbf"
wikidata_importance = "wikimedia-importance-2025-11.csv.gz"
languages = ["en", "de"]
name_analyzer = "standard"
geometry_mode = "geopoint-centroid"

[importance]
place = { city = 5.0, town = 4.0, village = 3.0 }
amenity = { restaurant = 2.0, school = 1.5 }
shop = { supermarket = 2.0 }
default = 1.0
